# Common
CLIENT_MAC = "client_mac"
WIRELESS_STATION = "wireless_station"
WIRELESS_ID = "wireless_id"
SRC_IP = "src_ip"
SENSOR_IP = "sensor_ip"
DST_IP = "dst_ip"
SENSOR_NAME = "sensor_name"
CLIENT_LATLNG = "client_latlong"
CLIENT_PROFILE = "client_profile"
CLIENT_RSSI = "client_rssi"
CLIENT_RSSI_NUM = "client_rssi_num"
CLIENT_SNR = "client_snr"
CLIENT_SNR_NUM = "client_snr_num"
TIMESTAMP = "timestamp"
FIRST_SWITCHED = "first_switched"
DURATION = "duration"
PKTS = "pkts"
BYTES = "bytes"
TYPE = "type"
SRC_VLAN = "src_vlan"
DST_VLAN = "dst_vlan"
WAN_VLAN = "wan_vlan"
LAN_VLAN = "lan_vlan"
DOT11STATUS = "dot11_status"
CLIENT_MAC_VENDOR = "client_mac_vendor"
CLIENT_ID = "client_id"
SRC_AS_NAME = "src_as_name"
SRC_AS = "src_as"
LAN_IP_AS_NAME = "lan_ip_as_name"
SRC_PORT = "src_port"
LAN_L4_PORT = "lan_l4_port"
SRC_MAP = "src_map"
SRV_PORT = "srv_port"
DST_AS_NAME = "dst_as_name"
WAN_IP_AS_NAME = "wan_ip_as_name"
DST_PORT = "dst_port"
WAN_L4_PORT = "wan_l4_port"
DST_MAP = "dst_map"
DST_AS = "dst_as"
ZONE_UUID = "zone_uuid"
APPLICATION_ID_NAME = "application_id_name"
BIFLOW_DIRECTION = "biflow_direction"
CONVERSATION = "conversation"
DIRECTION = "direction"
ENGINE_ID_NAME = "engine_id_name"
HTTP_HOST = "host"
HTTP_SOCIAL_MEDIA = "http_social_media"
HTTP_SOCIAL_USER = "http_social_user"
HTTP_USER_AGENT_OS = "http_user_agent"
HTTP_REFER_L1 = "referer"
IP_PROTOCOL_VERSION = "ip_protocol_version"
L4_PROTO = "l4_proto"
LAN_IP_NET_NAME = "lan_ip_net_name"
SRC_NET_NAME = "src_net_name"
WAN_IP_NET_NAME = "wan_ip_net_name"
DST_NET_NAME = "dst_net_name"
TOS = "tos"
DST_COUNTRY_CODE = "dst_country_code"
WAN_IP_COUNTRY_CODE = "wan_ip_country_code"
SRC_COUNTRY_CODE = "src_country_code"
SRC_COUNTRY = "src_country"
DST_COUNTRY = "dst_country"
LAN_IP_COUNTRY_CODE = "lan_ip_country_code"
SCATTERPLOT = "scatterplot"
INPUT_SNMP = "lan_interface_name"
OUTPUT_SNMP = "wan_interface_name"
INPUT_VRF = "input_vrf"
OUTPUT_VRF = "output_vrf"
SERVICE_PROVIDER = "service_provider"
SERVICE_PROVIDER_UUID = "service_provider_uuid"
SRC = "src"
LAN_IP = "lan_ip"
PUBLIC_IP = "public_ip"
IP_COUNTRY_CODE = "ip_country_code"
IP_AS_NAME = "ip_as_name"

BUILDING = "building"
BUILDING_UUID = "building_uuid"
CAMPUS = "campus"
CAMPUS_UUID = "campus_uuid"
FLOOR = "floor"
FLOOR_UUID = "floor_uuid"
ZONE = "zone"

COORDINATES_MAP = "coordinates_map"
HNBLOCATION = "hnblocation"
HNBGEOLOCATION = "hnbgeolocation"
RAT = "rat"
DOT11PROTOCOL = "dot11_protocol"
DEPLOYMENT = "deployment"
DEPLOYMENT_UUID = "deployment_uuid"
NAMESPACE = "namespace"
NAMESPACE_UUID = "namespace_uuid"
TIER = "tier"
MSG = "msg"
HTTPS_COMMON_NAME = "https_common_name"
TARGET_NAME = "target_name"

CLIENT_FULLNAME = "client_fullname"
PRODUCT_NAME = "product_name"

# Malware
HASH_SCORE = "hash_score"
IP_SCORE = "ip_score"
URL_SCORE = "url_score"
PROBE_HASH_SCORE = "hash_probe_score"
PROBE_IP_SCORE = "ip_probe_score"
PROBE_URL_SCORE = "url_probe_score"

URL = "url"
FILE_NAME = "file_name"
EMAIL_SENDER = "email_sender"
EMAIL_DESTINATION = "email_destination"
EMAIL_ID = "email_id"

# Event
ACTION = "action"
CLASSIFICATION = "classification"
DOMAIN_NAME = "domain_name"
ETHLENGTH_RANGE = "ethlength_range"
GROUP_NAME = "group_name"
SIG_GENERATOR = "sig_generator"
ICMPTYPE = "icmptype"
IPLEN_RANGE = "iplen_range"
REV = "rev"
SENSOR_UUID = "sensor_uuid"
PRIORITY = "priority"
SIG_ID = "sig_id"
ETHSRC = "ethsrc"
ETHSRC_VENDOR = "ethsrc_vendor"
ETHDST = "ethdst"
ETHDST_VENDOR = "ethdst_vendor"
DST = "dst"
WAN_IP = "wan_ip"
TTL = "ttl"
VLAN = "vlan"
MARKET = "market"
MARKET_UUID = "market_uuid"
ORGANIZATION = "organization"
ORGANIZATION_UUID = "organization_uuid"
CLIENT_LATLONG = "client_latlong"
HASH = "hash"
FILE_SIZE = "file_size"
SHA256 = "sha256"
FILE_URI = "file_uri"
FILE_HOSTNAME = "file_hostname"
GROUP_UUID = "group_uuid"
CLIENT_NAME = "client_name"

# Darklist
DARKLIST_SCORE = "darklist_score"
DARKLIST_SCORE_NAME = "darklist_score_name"
DARKLIST_PROTOCOL = "darklist_protocol"
DARKLIST_DIRECTION = "darklist_direction"
DARKLIST_CATEGORY = "darklist_category"

# NMSP
String NMSP_AP_MAC = "ap_mac"
String NMSP_RSSI = "rssi"
String NMSP_DOT11STATUS = "dot11_status"
String NMSP_VLAN_ID = "vlan_id"
String NMSP_DOT11PROTOCOL = "dot11_protocol"
String NMSP_WIRELESS_ID = "wireless_id"

# Location
LOC_TIMESTAMP_MILLIS = "timestampMillis"
SSID = "ssid"
LOC_MSEUDI = "mseUdi"
LOC_NOTIFICATIONS = "notifications"
LOC_NOTIFICATION_TYPE = "notificationType"
LOC_STREAMING_NOTIFICATION = "StreamingNotification"
LOC_LOCATION = "location"
LOC_GEOCOORDINATEv8 = "GeoCoordinate"
LOC_GEOCOORDINATEv9 = "geoCoordinate"
LOC_MAPINFOv8 = "MapInfo"
LOC_MAPINFOv9 = "mapInfo"
LOC_MAPCOORDINATEv8 = "MapCoordinate"
LOC_MACADDR = "macAddress"
LOC_MAP_HIERARCHY = "mapHierarchyString"
LOC_MAP_HIERARCHY_V10 = "locationMapHierarchy"
LOC_DOT11STATUS = "dot11Status"
LOC_SSID = "ssId"
LOC_IPADDR = "ipAddress"
LOC_AP_MACADDR = "apMacAddress"
LOC_SUBSCRIPTION_NAME = "subscriptionName"
LOC_LONGITUDE = "longitude"
LOC_LATITUDEv8 = "latitude"
LOC_LATITUDEv9 = "lattitude"
LOC_DEVICEID = "deviceId"
LOC_BAND = "band"
LOC_STATUS = "status"
LOC_USERNAME = "username"
LOC_ENTITY = "entity"
LOC_COORDINATE = "locationCoordinate"
LOC_COORDINATE_X = "x"
LOC_COORDINATE_Y = "y"
LOC_COORDINATE_Z = "z"
LOC_COORDINATE_UNIT = "unit"
WIRELESS_OPERATOR = "wireless_operator"
CLIENT_OS = "client_os"
INTERFACE_NAME = "interface_name"

# State
WIRELESS_CHANNEL = "wireless_channel"
WIRELESS_TX_POWER = "wireless_tx_power"
WIRELESS_ADMIN_STATE = "wireless_admin_state"
WIRELESS_OP_STATE = "wireless_op_state"
WIRELESS_MODE = "wireless_mode"
WIRELESS_SLOT = "wireless_slot"
WIRELESS_STATION_IP = "wireless_station_ip"
STATUS = "status"
WIRELESS_STATION_NAME = "wireless_station_name"

#Hashtag
VALUE = "value"

# Social
USER_SCREEN_NAME = "user_screen_name"
USER_NAME_SOCIAL = "user_name"
USER_ID = "user_id"
HASHTAGS = "hashtags"
MENTIONS = "mentions"
SENTIMENT = "sentiment"
MSG_SEND_FROM = "msg_send_from"
USER_FROM = "user_from"
USER_PROFILE_IMG_HTTPS = "user_profile_img_https"
INFLUENCE = "influence"
PICTURE_URL = "picture_url"
LANGUAGE = "language"
CATEGORY = "category"
FOLLOWERS = "followers"

#LOCATION
OLD_LOC = "old"
NEW_LOC = "new"
DWELL_TIME = "dwell_time"
TRANSITION = "transition"
SESSION = "session"
REPETITIONS = "repetitions"

# Radius
PACKET_SRC_IP_ADDRESS = "Packet-Src-IP-Address"
USER_NAME_RADIUS = "User-Name"
OPERATOR_NAME = "Operator-Name"
AIRESPACE_WLAN_ID = "Airespace-Wlan_Id"
CALLING_STATION_ID = "Calling-Station-Id"
ACCT_STATUS_TYPE = "Acct-Status-Type"
CALLED_STATION_ID = "Called-Station-Id"
CLIENT_ACCOUNTING_TYPE = "client_accounting_type"

# Pms
GUEST_NAME = "guest_name"
STAFF_NAME = "staff_name"
CLIENT_GENDER = "client_gender"
CLIENT_AUTH_TYPE = "client_auth_type"
AUTH_TYPE = "auth_type"
CLIENT_VIP = "client_vip"
CLIENT_LOYALITY = "client_loyality"

#Dwell
INDOW = "window"

#ICAP
PROXY_IP = "proxy_ip"

#Vault
PRI = "pri"
PRI_TEXT = "pri_text"
SYSLOG_FACILITY = "syslogfacility"
SYSLOG_FACILITY_TEXT = "syslogfacility_text"
SYSLOGSEVERITY = "syslogseverity"
SYSLOGSEVERITY_TEXT = "syslogseverity_text"
HOSTNAME = "hostname"
FROMHOST_IP = "fromhost_ip"
APP_NAME = "app_name"
PROXY_UUID = "proxy_uuid"
MESSAGE = "message"
SOURCE = "source"
TARGET = "target"
